function render(){let s=V.s;summaryLine.textContent=`${CFG[scope].label}: ${fmt(s.applications)} applications, ${fmt(s.decisions)} decisions considered, ${pct(s.grantRate)} grant rate and ${pct(s.refusalRate)} refusal rate.`;kpi('overviewKpis',[['Applications',fmt(s.applications),'Application volume'],['Decisions',fmt(s.decisions),'Issued + refused'],['Issued / Granted',fmt(s.issued),'Successful outcomes'],['Refused',fmt(s.refused),'Refused outcomes'],['Grant Rate',pct(s.grantRate),'Issued ÷ decisions'],['Refusal Rate',pct(s.refusalRate),'Refused ÷ decisions']]);kpi('applicationKpis',[['Applications',fmt(V.app.applications),'Selected volume'],['Average / Year',fmt(Math.round(V.app.avg||0)),'Selected years'],['Countries',fmt(V.app.countryCount||0),'Selected data'],['Highest Year',V.app.highestYear?.label||'-','Highest volume'],['Highest Country',V.app.highestCountry?.label||'-','Highest volume']]);kpi('outcomeKpis',[['Decisions',fmt(V.out.decisions),'Issued + refused'],['Issued / Granted',fmt(V.out.issued),'Successful outcomes'],['Refused',fmt(V.out.refused),'Refused outcomes'],['Grant Rate',pct(V.out.grantRate),'Issued ÷ decisions'],['Refusal Rate',pct(V.out.refusalRate),'Refused ÷ decisions']]);moves();profile();table();draw();renderCompare()}
function kpi(id,rows){document.getElementById(id).innerHTML=rows.map(r=>`<div class="kpi"><div class="kpi-label">${r[0]}</div><div class="kpi-value">${r[1]}</div><div class="kpi-sub">${r[2]}</div></div>`).join('')}
function moves(){let s=V.snap;if(!s)return;let r=s.c.refusalRate-s.p.refusalRate;movementCards.innerHTML=`<div class="move-card"><div class="move-label">Latest refusal rate change</div><div class="move-value ${r>0?'text-risk':'text-good'}">${spp(r)}</div><div class="kpi-sub">${s.cur.label} vs ${s.prev.label}</div></div>`}
function base(o={}){return{tooltip:{trigger:'axis'},grid:{left:54,right:24,top:34,bottom:54},legend:{bottom:4},xAxis:{type:'category'},yAxis:{type:'value',splitLine:{lineStyle:{color:C.g}}},...o}}
function chart(id,o){let el=document.getElementById(id);if(!el)return;if(!CH[id])CH[id]=echarts.init(el);CH[id].setOption(o,true)}
function draw(){bars('chartAnnual',V.yrRows,'applications','decisions');line('chartRefusalTrend',V.yrRows,'refusalRate',C.r,1);slope();line('chartQuarterApplications',V.qRows,'applications',C.a,0);bar('chartYearApplications',V.yrRows,'applications',C.a);hbar('chartTopApplications',topRows(V.a,'n','a'),C.a);bars('chartOutcomeYear',V.yrRows,'issued','refused');pie();bars('chartOutcomeQuarter',V.qRows,'issued','refused');bar('chartGrantTrend',V.yrRows,'issued',C.i);line('chartGrantRate',V.yrRows,'grantRate',C.i,1);hbar('chartTopGrants',V.nat.sort((a,b)=>b.issued-a.issued).slice(0,15).map(r=>({label:r.label,value:r.issued})),C.i);bar('chartRefusalVolume',V.yrRows,'refused',C.r);hbar('chartHighRefusal',V.hi.map(r=>({label:r.label,value:rd(r.refusalRate*100)})),C.r);hbar('chartCountryHigh',V.hi.map(r=>({label:r.label,value:rd(r.refusalRate*100)})),C.r);hbar('chartCountryLow',V.lo.map(r=>({label:r.label,value:rd(r.refusalRate*100)})),C.i);hbar('chartRefusalIncrease',V.nat.filter(r=>r.rrc>0).sort((a,b)=>b.rrc-a.rrc).slice(0,15).map(r=>({label:r.label,value:rd(r.rrc*100)})),C.r)}
function bars(id,r,a,b){chart(id,base({xAxis:{data:r.map(x=>x.label)},series:[{name:a,type:'bar',data:r.map(x=>x[a]),itemStyle:{color:a=='issued'?C.i:C.a}},{name:b,type:'bar',data:r.map(x=>x[b]),itemStyle:{color:b=='refused'?C.r:C.d}}]}))}
function bar(id,r,k,c){chart(id,base({xAxis:{data:r.map(x=>x.label)},series:[{type:'bar',data:r.map(x=>x[k]),itemStyle:{color:c}}]}))}
function line(id,r,k,c,rate){chart(id,base({xAxis:{data:r.map(x=>x.label),axisLabel:{rotate:35}},yAxis:{type:'value',axisLabel:rate?{formatter:'{value}%'}:{}},series:[{type:'line',data:r.map(x=>rate?rd(x[k]*100):x[k]),lineStyle:{color:c,width:3},itemStyle:{color:c},areaStyle:rate?undefined:{opacity:.1}}]}))}
function slope(){let s=V.snap;if(!s)return;chart('chartLatestSlope',base({xAxis:{data:[s.prev.label,s.cur.label]},yAxis:{type:'value',axisLabel:{formatter:'{value}%'}},series:[{type:'line',data:[rd(s.p.refusalRate*100),rd(s.c.refusalRate*100)],label:{show:true,formatter:'{c}%'},symbolSize:10,lineStyle:{color:C.r,width:3},itemStyle:{color:C.r}}]}))}
function hbar(id,r,c){if(!r.length)return;let d=r.slice().reverse();chart(id,{grid:{left:172,right:25,top:24,bottom:35},tooltip:{},xAxis:{type:'value'},yAxis:{type:'category',data:d.map(x=>x.label)},series:[{type:'bar',data:d.map(x=>x.value),itemStyle:{color:c}}]})}
function pie(){let s=V.out;chart('chartOutcomeMix',{color:[C.i,C.r],tooltip:{},legend:{bottom:0},series:[{type:'pie',radius:['48%','70%'],data:[{name:'Issued / Granted',value:s.issued},{name:'Refused',value:s.refused}]}]})}
function profile(){if(SEL.length!=1){countryProfile.classList.remove('show');countryProfile.innerHTML='';return}let r=V.nat.find(x=>x.label==SEL[0]);countryProfile.classList.add('show');countryProfile.innerHTML=`<h2>${e(r.label)}</h2><p>${CFG[scope].label} profile.</p><div class="profile-stats">${[['Applications',fmt(r.applications)],['Decisions',fmt(r.decisions)],['Issued / Granted',fmt(r.issued)],['Refused',fmt(r.refused)],['Grant Rate',pct(r.grantRate)],['Refusal Rate',pct(r.refusalRate)],['Movement',`<span class="${r.mclass}">${e(r.mtext)}</span>`]].map(x=>`<div class="profile-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`}
function table(){countryTable.innerHTML=`<table><thead><tr><th>Nationality</th><th>Applications</th><th>Decisions</th><th>Issued</th><th>Refused</th><th>Grant Rate</th><th>Refusal Rate</th><th>Application Change</th><th>Grant Change</th><th>Refusal Rate Change</th><th>Movement</th></tr></thead><tbody>${V.nat.map(r=>`<tr><td>${e(r.label)}</td><td>${fmt(r.applications)}</td><td>${fmt(r.decisions)}</td><td>${fmt(r.issued)}</td><td>${fmt(r.refused)}</td><td>${pct(r.grantRate)}</td><td>${pct(r.refusalRate)}</td><td>${spct(r.ac)}</td><td>${spct(r.gc)}</td><td>${spp(r.rrc)}</td><td><span class="move-text ${r.mclass}">${e(r.mtext)}</span></td></tr>`).join('')}</tbody></table>`}
function exportCountryCsv(){csv('ukvi-country-summary.csv',[['Nationality','Applications','Decisions','Issued','Refused','Grant Rate','Refusal Rate','Movement']].concat(V.nat.map(r=>[r.label,r.applications,r.decisions,r.issued,r.refused,pct(r.grantRate),pct(r.refusalRate),r.mtext])))}
function renderCompareSlots(v=['India','Pakistan']){compareSlots.innerHTML=v.map((x,i)=>`<div class="compare-slot"><input list="countryOptions" class="compare-country" placeholder="Country ${i+1}" value="${e(x)}"><button class="icon-btn" onclick="this.closest('.compare-slot').remove()">×</button></div>`).join('')}
function addCompareSlot(){let v=[...document.querySelectorAll('.compare-country')].map(i=>i.value);if(v.length<5){v.push('');renderCompareSlots(v)}}
function resetCompare(){renderCompareSlots();renderCompare()}
function toggleCompareMode(){document.querySelectorAll('.compare-period').forEach(x=>x.style.display=compareMode.value=='period'?'block':'none');document.querySelectorAll('.compare-trend').forEach(x=>x.style.display=compareMode.value=='trend'?'block':'none')}
function renderCompare(){let cs=u([...document.querySelectorAll('.compare-country')].map(i=>cl(i.value)).filter(x=>N.includes(x)));let m=compareMetric.value;if(!cs.length)return;let rows=cs.map(c=>{let s={...apps(V.a.filter(x=>x.n==c)),...outs(V.o.filter(x=>x.n==c))};return{country:c,value:m.includes('Rate')?rd(s[m]*100):s[m],s}});bar('chartCompare',rows.map(r=>({label:r.country,[m]:r.value})),m,m.includes('Rate')?C.r:C.a);compareTable.innerHTML=`<table><thead><tr><th>Country</th><th>${m}</th><th>Applications</th><th>Decisions</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.country)}</td><td>${m.includes('Rate')?pct(r.value/100):fmt(r.value)}</td><td>${fmt(r.s.applications)}</td><td>${fmt(r.s.decisions)}</td></tr>`).join('')}</tbody></table>`}
