
const FILE='./UKVI%20Data%202020-2026%20Q2.xlsx',MIN=30;
const CFG={overall:{label:'Overall Study Visa',sub:'All study visa subtypes, including main applicants and dependants.',app:['Applied'],out:['Outcomes']},sponsored:{label:'Sponsored Study Only',sub:'Sponsored study / student visa applications and outcomes for main applicants only.',app:['Sponsored Applied'],out:['Sponsored Outcomes','Sponsored study']}};
const C={a:'#2f80c0',d:'#64748b',i:'#15836f',r:'#c0392b',w:'#a16207',g:'#e5eaf0'};
let wb,scope='sponsored',A=[],O=[],Y=[],N=[],SEL=[],V={},CH={};
document.addEventListener('click',e=>{if(countryBox&&!countryBox.contains(e.target))closeCountryMenu()});
addEventListener('resize',()=>Object.values(CH).forEach(c=>c&&c.resize()));
async function load(){try{let r=await fetch(FILE,{cache:'force-cache'});if(!r.ok)throw Error('Could not load workbook');wb=XLSX.read(await r.arrayBuffer(),{type:'array'});loadScope(scope);applyFilters();set('guideLoaded',new Date().toLocaleString('en-GB'))}catch(e){err(e.message||e)}finally{loader.style.display='none'}}
function loadScope(s){scope=s;let c=CFG[s];A=readA(c.app);O=readO(c.out);Y=u(A.map(x=>x.y).concat(O.map(x=>x.y))).sort((a,b)=>a-b);N=u(A.map(x=>x.n).concat(O.map(x=>x.n))).sort((a,b)=>a.localeCompare(b));set('reportTitle',c.label);set('topScope',c.label);set('reportSubtitle',c.sub);document.querySelectorAll('.scope-btn').forEach(b=>b.classList.toggle('active',b.dataset.scope==s));fill(yearFrom,Y,Y[0]);fill(yearTo,Y,Y.at(-1));fill(compareYear,Y,Y.at(-1));countryOptions.innerHTML=N.map(n=>`<option value="${e(n)}"></option>`).join('');renderCountryMenu();set('guideLatest',lastPeriod()||'-');renderCompareSlots()}
function setScope(s){SEL=[];loadScope(s);applyFilters()}
function sh(n){return wb.Sheets[n]||wb.Sheets[wb.SheetNames.find(x=>cl(x).toLowerCase()==cl(n).toLowerCase())]}
function readA(ns){let m={};ns.forEach(n=>{let s=sh(n);if(!s)return;XLSX.utils.sheet_to_json(s,{defval:''}).forEach(r=>{let y=yr(r.Year,r.Quarter),q=qt(r.Quarter),c=cl(r.Nationality),a=num(r.Applications);if(y&&q&&c&&a){let k=`${y}|${q}|${c}`;m[k]=m[k]||{y,q,n:c,a:0};m[k].a+=a}})});return Object.values(m)}
function readO(ns){let m={};ns.forEach(n=>{let s=sh(n);if(!s)return;XLSX.utils.sheet_to_json(s,{defval:''}).forEach(r=>{let o=oc(r['Case outcome']||r.Outcome),y=yr(r.Year,r.Quarter),q=qt(r.Quarter),c=cl(r.Nationality),d=num(r.Decisions);if(o&&y&&q&&c&&d){let k=`${y}|${q}|${c}|${o}`;m[k]=m[k]||{y,q,n:c,o,d:0};m[k].d+=d}})});return Object.values(m)}
function fill(el,vals,val){el.innerHTML='';vals.forEach(v=>el.add(new Option(v,v)));el.value=val}
function f(){return{yf:+yearFrom.value||Y[0],yt:+yearTo.value||Y.at(-1),q:quarter.value,ns:SEL}}
function applyFilters(){let x=f(),a=A.filter(r=>r.y>=x.yf&&r.y<=x.yt&&(x.q=='All'||r.q==x.q)&&(!x.ns.length||x.ns.includes(r.n))),o=O.filter(r=>r.y>=x.yf&&r.y<=x.yt&&(x.q=='All'||r.q==x.q)&&(!x.ns.length||x.ns.includes(r.n)));V=build(a,o,x);activeFilterText.textContent='Current filters: '+[`${x.yf} to ${x.yt}`,x.q=='All'?'':x.q,!SEL.length?'All countries':SEL.length==1?SEL[0]:SEL.length+' countries selected'].filter(Boolean).join(' | ');render();closeCountryMenu()}
function resetFilters(){SEL=[];yearFrom.value=Y[0];yearTo.value=Y.at(-1);quarter.value='All';countrySearch.value='';renderCountryMenu();applyFilters()}
function build(a,o,x){let app=apps(a),out=outs(o),nat=nats(a,o,x),yrRows=u(a.map(r=>r.y).concat(o.map(r=>r.y))).sort((a,b)=>a-b).map(y=>({label:String(y),...apps(a.filter(r=>r.y==y)),...outs(o.filter(r=>r.y==y))})),qRows=periods(a,o).map(p=>({label:p.label,...apps(a.filter(r=>r.y==p.y&&r.q==p.q)),...outs(o.filter(r=>r.y==p.y&&r.q==p.q))}));return{a,o,x,app,out,s:{...app,...out},nat,yrRows,qRows,snap:snap(a,o),hi:nat.filter(r=>r.decisions>=MIN).sort((a,b)=>b.refusalRate-a.refusalRate).slice(0,15),lo:nat.filter(r=>r.decisions>=MIN).sort((a,b)=>a.refusalRate-b.refusalRate).slice(0,15)}}
function apps(a){let applications=sum(a,'a'),yrs=new Set(a.map(r=>r.y)),cs=new Set(a.map(r=>r.n));return{applications,avg:yrs.size?applications/yrs.size:0,countryCount:cs.size,highestYear:top(a,'y','a'),highestCountry:top(a,'n','a')}}
function outs(o){let issued=0,refused=0;o.forEach(r=>r.o=='issued'?issued+=r.d:refused+=r.d);let decisions=issued+refused;return{decisions,issued,refused,grantRate:decisions?issued/decisions:0,refusalRate:decisions?refused/decisions:0}}
function nats(a,o,x){return u(a.map(r=>r.n).concat(o.map(r=>r.n))).sort().map(n=>{let row={label:n,...apps(a.filter(r=>r.n==n)),...outs(o.filter(r=>r.n==n))};return mv(row,n,x)}).sort((a,b)=>b.applications-a.applications)}
function mv(row,n,x){let cy=Math.max(...u(A.concat(O).filter(r=>r.n==n&&r.y>=x.yf&&r.y<=x.yt).map(r=>r.y))),py=cy-1,qs=x.q=='All'?u(A.concat(O).filter(r=>r.n==n&&r.y==cy).map(r=>r.q)):[x.q],ca=apps(A.filter(r=>r.n==n&&r.y==cy&&qs.includes(r.q))),pa=apps(A.filter(r=>r.n==n&&r.y==py&&qs.includes(r.q))),co=outs(O.filter(r=>r.n==n&&r.y==cy&&qs.includes(r.q))),po=outs(O.filter(r=>r.n==n&&r.y==py&&qs.includes(r.q)));if(!pa.applications&&!po.decisions)return{...row,ac:null,gc:null,rrc:null,mtext:'– Insufficient Data',mclass:'text-neutral'};let ac=chg(ca.applications,pa.applications),gc=chg(co.issued,po.issued),rrc=co.refusalRate-po.refusalRate,l=lab(ac,gc,rrc);return{...row,ac,gc,rrc,mtext:l[0],mclass:l[1],score:Math.max(0,Math.min(100,Math.round(50+(ac>.05?10:ac<-.05?-5:0)+(gc>.05?15:gc<-.05?-10:0)+(rrc<-.005?25:rrc>.005?-25:0))))}}
function lab(a,g,r){let up=a>.05,down=a<-.05,gd=g>.05,gb=g<-.05,better=r<-.005,worse=r>.005;if(up&&gd&&better)return['↗ Positive Growth','text-good'];if(up&&better)return['↗ Higher Volume, Better Outcome','text-good'];if(down&&better)return['↘ Lower Volume, Better Outcome','text-good'];if(up&&worse)return['⚠ Higher Volume, Higher Risk','text-warn'];if((down&&worse)||(gb&&worse))return['↓ Declining','text-risk'];return['→ Stable / Mixed','text-warn']}
function periods(a,o){let m={};a.concat(o).forEach(r=>m[`${r.y}|${r.q}`]={y:r.y,q:r.q,label:`${r.y} ${r.q}`});return Object.values(m).sort((a,b)=>a.y-b.y||Number(a.q[1])-Number(b.q[1]))}
function snap(a,o){let p=periods(a,o);if(!p.length)return null;let c=p.at(-1),pr={y:c.y-1,q:c.q,label:`${c.y-1} ${c.q}`};return{cur:c,prev:pr,c:outs(o.filter(r=>r.y==c.y&&r.q==c.q)),p:outs(o.filter(r=>r.y==pr.y&&r.q==pr.q))}}
